#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────
#  sats.fast installer
#  Target: Ubuntu 22.04 / Debian 12
#  Usage:  curl -sSL https://raw.githubusercontent.com/pseudozach/sats.fast/main/scripts/install.sh | bash
# ─────────────────────────────────────────────────────────

INSTALL_DIR="/opt/sats-fast"
DATA_DIR="$INSTALL_DIR/data"

echo ""
echo "  ⚡ sats.fast installer"
echo "  ─────────────────────────────────────"
echo ""

# Ensure we can read from terminal even when piped
exec </dev/tty

# ── 1. System packages ────────────────────────────────
echo "📦 Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y git curl sqlite3 nginx build-essential

# ── 2. Node.js 22 via NodeSource ──────────────────────
if ! command -v node &>/dev/null || [[ $(node -v | cut -d. -f1 | tr -d 'v') -lt 22 ]]; then
  echo "📦 Installing Node.js 22..."
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
echo "   Node.js $(node -v)"

# ── 3. pnpm + pm2 ─────────────────────────────────────
if ! command -v pnpm &>/dev/null; then
  echo "📦 Installing pnpm..."
  sudo npm install -g pnpm
fi
if ! command -v pm2 &>/dev/null; then
  echo "📦 Installing pm2..."
  sudo npm install -g pm2
fi

# ── 4. Clone or update repo ───────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  echo "📥 Updating existing installation..."
  cd "$INSTALL_DIR"
  git pull --rebase
else
  echo "📥 Cloning sats.fast..."
  sudo mkdir -p "$INSTALL_DIR"
  sudo chown "$USER:$USER" "$INSTALL_DIR"
  git clone https://github.com/pseudozach/sats.fast.git "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ── 5. Install dependencies + build ───────────────────
echo "📦 Installing dependencies..."
pnpm install --frozen-lockfile 2>/dev/null || pnpm install
echo "🔨 Building..."
pnpm build

# ── 6. Interactive configuration ──────────────────────
echo ""
echo "  🔧 Configuration"
echo "  ─────────────────────────────────────"
echo ""

read -rp "  Telegram bot token (from @BotFather): " TELEGRAM_BOT_TOKEN
while [ -z "$TELEGRAM_BOT_TOKEN" ]; do
  read -rp "  ⚠️  Required. Telegram bot token: " TELEGRAM_BOT_TOKEN
done

echo ""
echo "  Breez API key is free. Get one at:"
echo "  https://breez.technology/request-api-key/#contact-us-form-sdk"
read -rp "  Breez API key: " BREEZ_API_KEY
while [ -z "$BREEZ_API_KEY" ]; do
  read -rp "  ⚠️  Required. Breez API key: " BREEZ_API_KEY
done

echo ""
read -rp "  Admin username [admin]: " ADMIN_USERNAME
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

while true; do
  read -rsp "  Admin password: " ADMIN_PASSWORD
  echo ""
  read -rsp "  Confirm password: " ADMIN_PASSWORD2
  echo ""
  if [ "$ADMIN_PASSWORD" = "$ADMIN_PASSWORD2" ] && [ -n "$ADMIN_PASSWORD" ]; then
    break
  fi
  echo "  ⚠️  Passwords don't match or are empty. Try again."
done

ADMIN_PASSWORD_HASH=$(node -e "const b=require('bcryptjs');console.log(b.hashSync('$ADMIN_PASSWORD',10))")

echo ""
echo "  AI Provider (users can override per-user)"
read -rp "  Default AI provider [anthropic/openai] (anthropic): " DEFAULT_AI_PROVIDER
DEFAULT_AI_PROVIDER="${DEFAULT_AI_PROVIDER:-anthropic}"

read -rp "  Default AI model (claude-sonnet-4-20250514): " DEFAULT_AI_MODEL
DEFAULT_AI_MODEL="${DEFAULT_AI_MODEL:-claude-sonnet-4-20250514}"

read -rp "  Default AI API key (optional, users can set their own): " DEFAULT_AI_KEY

MASTER_ENCRYPTION_KEY=$(openssl rand -hex 32)
SESSION_SECRET=$(openssl rand -hex 32)

# ── 7. Write .env ──────────────────────────────────────
cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install.sh on $(date -u)
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
MASTER_ENCRYPTION_KEY=$MASTER_ENCRYPTION_KEY
BREEZ_API_KEY=$BREEZ_API_KEY
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD_HASH=$ADMIN_PASSWORD_HASH

DEFAULT_AI_PROVIDER=$DEFAULT_AI_PROVIDER
DEFAULT_AI_MODEL=$DEFAULT_AI_MODEL
$([ "$DEFAULT_AI_PROVIDER" = "openai" ] && echo "DEFAULT_OPENAI_KEY=$DEFAULT_AI_KEY" || echo "DEFAULT_ANTHROPIC_KEY=$DEFAULT_AI_KEY")

NODE_ENV=production
PORT=3000
DATA_DIR=$DATA_DIR
DATABASE_URL=$DATA_DIR/sats.db
SESSION_SECRET=$SESSION_SECRET
EOF

chmod 600 "$INSTALL_DIR/.env"

# ── 8. Run migrations ─────────────────────────────────
echo "📦 Running database migrations..."
mkdir -p "$DATA_DIR"
pnpm db:migrate

# ── 9. pm2 ─────────────────────────────────────────────
echo "🚀 Starting with pm2..."
pm2 delete sats-fast-bot 2>/dev/null || true
pm2 delete sats-fast-admin 2>/dev/null || true
pm2 start ecosystem.config.js
pm2 save
pm2 startup -u "$USER" --hp "$HOME" 2>/dev/null || true

# ── 10. Nginx reverse proxy ────────────────────────────
SERVER_IP=$(curl -4 -s ifconfig.me 2>/dev/null || echo "localhost")

sudo tee /etc/nginx/sites-available/sats-fast > /dev/null <<EOF
server {
    listen 80;
    server_name $SERVER_IP;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF

sudo ln -sf /etc/nginx/sites-available/sats-fast /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx

# ── Done! ──────────────────────────────────────────────
echo ""
echo "  ─────────────────────────────────────"
echo "  ✅ sats.fast is running!"
echo ""
echo "  Admin panel:  http://$SERVER_IP/"
echo "  Telegram bot: running via pm2"
echo ""
echo "  Logs:   pm2 logs"
echo "  Stop:   pm2 stop all"
echo "  Status: pm2 status"
echo ""
echo "  ⚠️  Back up your .env file — it contains"
echo "     your encryption key and credentials."
echo "  ─────────────────────────────────────"
echo ""
